package com.github.terrakok.flowmarbles.theme

import androidx.compose.ui.graphics.Color

// Black & White theme palette — pure monochrome

internal val Seed = Color(0xFF000000)

// Light theme (white surface, black text)
internal val PrimaryLight = Color(0xFF000000)
internal val OnPrimaryLight = Color(0xFFFFFFFF)
internal val PrimaryContainerLight = Color(0xFFE0E0E0)
internal val OnPrimaryContainerLight = Color(0xFF000000)
internal val SecondaryLight = Color(0xFF424242)
internal val OnSecondaryLight = Color(0xFFFFFFFF)
internal val SecondaryContainerLight = Color(0xFFE0E0E0)
internal val OnSecondaryContainerLight = Color(0xFF212121)
internal val TertiaryLight = Color(0xFF616161)
internal val OnTertiaryLight = Color(0xFFFFFFFF)
internal val TertiaryContainerLight = Color(0xFFE0E0E0)
internal val OnTertiaryContainerLight = Color(0xFF303030)
internal val ErrorLight = Color(0xFFB00020)
internal val OnErrorLight = Color(0xFFFFFFFF)
internal val ErrorContainerLight = Color(0xFFFFDAD6)
internal val OnErrorContainerLight = Color(0xFF410002)
internal val BackgroundLight = Color(0xFFFFFFFF)
internal val OnBackgroundLight = Color(0xFF1C1B1F)
internal val SurfaceLight = Color(0xFFFFFFFF)
internal val OnSurfaceLight = Color(0xFF1C1B1F)
internal val SurfaceVariantLight = Color(0xFFE7E0EC)
internal val OnSurfaceVariantLight = Color(0xFF49454E)
internal val OutlineLight = Color(0xFF7A7580)
internal val OutlineVariantLight = Color(0xFFCAC4D0)
internal val ScrimLight = Color(0xFF000000)
internal val InverseSurfaceLight = Color(0xFF312F34)
internal val InverseOnSurfaceLight = Color(0xFFF4EFF4)
internal val InversePrimaryLight = Color(0xFFD0BCFF)
internal val SurfaceDimLight = Color(0xFFE4E0E6)
internal val SurfaceBrightLight = Color(0xFFFFFFFF)
internal val SurfaceContainerLowestLight = Color(0xFFFFFFFF)
internal val SurfaceContainerLowLight = Color(0xFFFEFAFF)
internal val SurfaceContainerLight = Color(0xFFF8F3F9)
internal val SurfaceContainerHighLight = Color(0xFFF2EDF3)
internal val SurfaceContainerHighestLight = Color(0xFFECE7ED)

// Dark theme (black surface, white text)
internal val PrimaryDark = Color(0xFFFFFFFF)
internal val OnPrimaryDark = Color(0xFF000000)
internal val PrimaryContainerDark = Color(0xFF212121)
internal val OnPrimaryContainerDark = Color(0xFFFFFFFF)
internal val SecondaryDark = Color(0xFFD0BCFF)
internal val OnSecondaryDark = Color(0xFF381E72)
internal val SecondaryContainerDark = Color(0xFF4F378A)
internal val OnSecondaryContainerDark = Color(0xFFEADDFF)
internal val TertiaryDark = Color(0xFFB8C9FF)
internal val OnTertiaryDark = Color(0xFF182D6C)
internal val TertiaryContainerDark = Color(0xFF35478A)
internal val OnTertiaryContainerDark = Color(0xFFDDE3FF)
internal val ErrorDark = Color(0xFFFFB4AB)
internal val OnErrorDark = Color(0xFF690005)
internal val ErrorContainerDark = Color(0xFF93000A)
internal val OnErrorContainerDark = Color(0xFFFFDAD6)
internal val BackgroundDark = Color(0xFF000000)
internal val OnBackgroundDark = Color(0xFFE6E1E5)
internal val SurfaceDark = Color(0xFF000000)
internal val OnSurfaceDark = Color(0xFFE6E1E5)
internal val SurfaceVariantDark = Color(0xFF49454E)
internal val OnSurfaceVariantDark = Color(0xFFCAC4D0)
internal val OutlineDark = Color(0xFF938F99)
internal val OutlineVariantDark = Color(0xFF49454E)
internal val ScrimDark = Color(0xFF000000)
internal val InverseSurfaceDark = Color(0xFFE6E1E5)
internal val InverseOnSurfaceDark = Color(0xFF312F34)
internal val InversePrimaryDark = Color(0xFF483B63)
internal val SurfaceDimDark = Color(0xFF000000)
internal val SurfaceBrightDark = Color(0xFF27262A)
internal val SurfaceContainerLowestDark = Color(0xFF060607)
internal val SurfaceContainerLowDark = Color(0xFF131216)
internal val SurfaceContainerDark = Color(0xFF17161A)
internal val SurfaceContainerHighDark = Color(0xFF212024)
internal val SurfaceContainerHighestDark = Color(0xFF2C2B2F)
